###################################################
#                                                 #
#                  [DerpTemplate]                 #
#                                                 #
#   Authors: AnonymousBluejay                     #
#                                                 #
#                                                 #
###################################################

#Add config here