###################################################
#                                                 #
#                  [FinElemental]                 #
#                                                 #
#   Authors: plugin gang                          #
#                                                 #
#                                                 #
###################################################

#Add config here