name: FinchElementalDamage
version: 1.0
api-version: 1.19
authors: [AnonymousBluejay,Soup,Samyed]
website: passerines.dev
main: net.passerines.finch.FinchElementalDamage
description: A class project
depend: [ProtocolLib, Vault]

commands:
  finch:
    description: finch
    permission: finch.user

  reforge:
    description: reforges item in sender's hand
    permission: finch.admin

  ench:
    description: enchants item in sender's hand
    permissions: finch.admin

  getplayers:
    description: gets players list
    permission: finch.admin

  getehp:
    description: gets player's ehp
    permission: finch.user

  finchattributes:
    description: sets max health
    permission: finch.admin

  itemgive:
    description: gives and item
    permission: finch.admin

  trinketmenu:
    description: opens the trinkets menu
    permission: finch.user

permissions:
  finch.admin:
    description: Permission to do everything
    default: op
  finch.user:
    description: Permission to use cosmetic commands
    default: true