name: DerpTemplate
version: 1.0
api-version: 1.18
author: AnonymousBluejay
website: passerines.dev
main: net.passerines.derp.Derp
description: Template plugin
depend: []

commands:
  derp:
    description: derp
    permission: derp.user

permissions:
  derp.user:
    description: Permission to use /derp
    default: true