name: FinchElementalDamage
version: 1.0
api-version: 1.18
authors: [AnonymousBluejay,Soup,Samyed]
website: passerines.dev
main: net.passerines.finch.FinchElementalDamage
description: A class project
depend: [ProtocolLib]

commands:
  finch:
    description: finch
    permission: finch.user

  getplayers:
    description: gets players list
    permission: finch.user

  finchattributes:
    description: sets max health
    permission: finch.user
  itemgive:
    description: gives and item
    permission: finch.admin

permissions:
  finch.admin:
    description: Permission to do everything
    default: op
  finch.user:
    description: Permission to use /finch
    default: true