name: FinchElementalDamage
version: 1.0
api-version: 1.18
authors: [AnonymousBluejay,Soup,Samyed]
website: passerines.dev
main: net.passerines.finch.FinchElementalDamage
description: A class project
depend: []

commands:
  finch:
    description: finch
    permission: finch.user

permissions:
  finch.user:
    description: Permission to use /finch
    default: true